import './globals.css'

import type { Metadata } from 'next'
import { Sora } from 'next/font/google'

import { Header } from '@/components/header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const sora = Sora({
  display: 'swap',
  subsets: ['latin'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${sora.className} antialiased bg-[#FCFCFC] w-full`}>
        <Header />
        {children}
      </body>
    </html>
  )
}
